[[redirects]]
  from = "/api/"
  to = "https://budget-planner-api.up.railway.app/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for ="/"
    [headers.values]
    Access-Control-Allow-Origin = "*"