[[redirects]]
  from = "/v1/"
  to = "https://budget-planner-api.up.railway.app"
  status = 200
  force = true
  headers = {X-From = "netlify"}

[[headers]]
  for ="/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"